# Generated by Django 3.2.8 on 2021-11-09 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_text_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
    ]
