# Generated by Django 3.2.8 on 2021-11-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='uploads/avatar1.jpg', upload_to='uploads'),
        ),
    ]
